const asyncHandler = require('express-async-handler')
const Goal = require('../models/goalModel')
const User = require('../models/userModel')
const { YoutubeTranscript } = require('youtube-transcript')
const he = require('he')

// @desc    Get user goals
// @route   GET /api/goals
// @access  Private
const getGoals = asyncHandler(async (req, res) => {
  const goals = await Goal.find({ user: req.user.id }).sort({ createdAt: -1 }) // ترتيب بالأحدث
  res.status(200).json(goals)
})

// @desc    Create new goal (Transcript + AI Generation)
// @route   POST /api/goals
// @access  Private
const setGoal = asyncHandler(async (req, res) => {
  if (!req.body.text) {
    res.status(400)
    throw new Error('Please add a text field')
  }

  let transcriptText = ''
  
  // 1. Transcript Fetching (With Fallback)
  try {
    console.log('🔄 Fetching transcript...')
    const transcriptObj = await YoutubeTranscript.fetchTranscript(req.body.text, {
      lang: 'en', country: 'US',
    })

    if (transcriptObj && transcriptObj.length > 0) {
      transcriptText = transcriptObj.map((item) => he.decode(item.text)).join(' ').replace(/\s+/g, ' ').trim()
      console.log(`✅ Transcript Success! Length: ${transcriptText.length}`)
    }
  } catch (error) {
    console.log(`⚠️ Youtube blocked scraper. Using Simulated Text.`)
    transcriptText = `This is a simulated transcript from the video. In a real scenario, this text would come from the video itself. But for now, we are using this placeholder to test the AI generation workflow.`
  }

  if (!transcriptText) transcriptText = "No transcript available."

  // 2. AI Content Generation (Simulated)
  console.log('🤖 Generating AI Content (Simulated)...')
  
  const simulatedBlogPost = `
    ## The Future of Tech: A Deep Dive
    
    Based on the video "${req.body.text}", we explore key concepts.
    This is an auto-generated blog post simulation. 
    
    **Key Takeaways:**
    1. Innovation is key.
    2. AI is changing everything.
    3. Consistency matters.
    
    *Generated by EchoSuite AI*
  `

  const simulatedTweets = [
    "🚀 Just watched an amazing video! #Tech #Innovation",
    "💡 Did you know that AI is reshaping our future? Here is why. #AI #Future",
    "🔥 Consistency is the secret sauce to success. Don't give up! #Motivation",
    "👀 Check out this insights from the latest video. Mind blown! 🤯",
    "✨ EchoSuite is making content creation easier than ever. #SaaS #Startup"
  ]

  // 3. Save to Database
  const goal = await Goal.create({
    text: req.body.text,
    transcript: transcriptText,
    blogPost: simulatedBlogPost,  // حفظ المقال
    tweets: simulatedTweets,      // حفظ التغريدات
    user: req.user.id,
  })

  res.status(200).json(goal)
})

// @desc    Update goal
// @route   PUT /api/goals/:id
// @access  Private
const updateGoal = asyncHandler(async (req, res) => {
  const goal = await Goal.findById(req.params.id)
  if (!goal) { res.status(400); throw new Error('Goal not found'); }
  if (!req.user) { res.status(401); throw new Error('User not found'); }
  if (goal.user.toString() !== req.user.id) { res.status(401); throw new Error('User not authorized'); }
  const updatedGoal = await Goal.findByIdAndUpdate(req.params.id, req.body, { new: true })
  res.status(200).json(updatedGoal)
})

// @desc    Delete goal
// @route   DELETE /api/goals/:id
// @access  Private
const deleteGoal = asyncHandler(async (req, res) => {
  const goal = await Goal.findById(req.params.id)
  if (!goal) { res.status(400); throw new Error('Goal not found'); }
  if (!req.user) { res.status(401); throw new Error('User not found'); }
  if (goal.user.toString() !== req.user.id) { res.status(401); throw new Error('User not authorized'); }
  await goal.deleteOne()
  res.status(200).json({ id: req.params.id })
})

module.exports = { getGoals, setGoal, updateGoal, deleteGoal }
