import { Link } from 'react-router-dom'

function Terms() {
  return (
    <div style={{ maxWidth: '800px', margin: '50px auto', padding: '20px', lineHeight: '1.6' }}>
      <Link to="/" className='btn' style={{ marginBottom: '20px' }}>Back to Home</Link>
      <h1 style={{ marginBottom: '20px' }}>Terms of Service</h1>
      <p style={{ color: '#666' }}>Last updated: February 2026</p>
      
      <h3 style={{ marginTop: '20px' }}>1. Acceptance of Terms</h3>
      <p>By accessing and using EchoSuite, you accept and agree to be bound by the terms and provision of this agreement.</p>

      <h3 style={{ marginTop: '20px' }}>2. Use of Service</h3>
      <p>You agree to use EchoSuite only for lawful purposes. You are responsible for all content generated using your account.</p>

      <h3 style={{ marginTop: '20px' }}>3. Intellectual Property</h3>
      <p>The content generated by our AI is yours to use. However, the EchoSuite brand and software remain our property.</p>

      <h3 style={{ marginTop: '20px' }}>4. Termination</h3>
      <p>We reserve the right to terminate your access to the site without any advance notice.</p>
    </div>
  )
}

export default Terms
